openapi: 3.0.0
info:
  title: Google OpenID API
  version: 1.0.0

paths:
  /token:
    post:
      summary: Initiate new session
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                code:
                  type: string
                client_id:
                  type: string
                client_secret:
                  type: string
                redirect_uri:
                  type: string
                grant_type:
                  type: string
              required:
                - code
                - client_id
                - client_secret
                - redirect_uri
                - grant_type
      responses:
        '200':
          description: New session response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'

components:
  schemas:
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        expires_in:
          type: number
        id_token:
          type: string
        scope:
          type: array
          items:
            type: string
        token_type:
          type: string
        refresh_token:
          type: string
      required:
        - id_token
        - scope
