openapi: 3.0.0
info:
  title: Simple Items API
  version: 1.0.0

paths:
  /session/new:
    post:
      summary: Initiate new session
      parameters:
        - name: X-Idempotency-Token
          in: header
          schema:
            type: string
          required: true
      responses:
        '200':
          description: New session response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewSessionResponse'
        '429':
          description: Too many requests

components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
      required:
        - id
        - name
        - price

    NewItem:
      type: object
      properties:
        name:
          type: string
        price:
          type: number
      required:
        - name
        - price
